id = "wxml-zed"
name = "WXML"
description = "WXML (WeiXin Markup Language) support for Zed."
version = "0.3.0"
schema_version = 1
authors = ["zscumt123", "wxml-zed contributors"]
repository = "https://github.com/zscumt123/wxml-zed"

snippets = ["./snippets/wxml.json"]

[language_servers.wxml-lsp]
name = "WXML LSP"
languages = ["WXML"]

[language_servers.wxml-lsp.language_ids]
WXML = "wxml"

[grammars.wxml]
repository = "https://github.com/zscumt123/tree-sitter-wxml"
rev = "fef7ea7277adba1cc697afd01c588da8c2c6e944"
