("<" @open "/>" @close)
("</" @open ">" @close)
("<" @open ">" @close)
("\"" @open "\"" @close)
((element (start_tag) @open (end_tag) @close) (#set! newline.only))
((block_element (block_start_tag) @open (block_end_tag) @close) (#set! newline.only))
((slot_element (slot_start_tag) @open (slot_end_tag) @close) (#set! newline.only))
((template_element (template_start_tag) @open (template_end_tag) @close) (#set! newline.only))
((wxs_element (wxs_start_tag) @open (wxs_end_tag) @close) (#set! newline.only))
